# Generated by Django 3.0.dev20190416084545 on 2020-01-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.TextField()),
                ('kategoria', models.TextField()),
                ('nazwa', models.TextField()),
                ('kwota', models.TextField()),
            ],
        ),
    ]
